#!/usr/bin/env node

const axios = require('axios');

async function generateStockNewsReport() {
  const baseUrl = 'http://localhost:3000';
  
  try {
    console.log('🔍 Generating Stock News Report for India...\n');
    
    // Get current stats
    console.log('📊 Getting current crawler stats...');
    const statsResponse = await axios.get(`${baseUrl}/api/v1/stats`);
    const stats = statsResponse.data.stats;
    
    console.log(`✅ Found ${stats.totalPages} pages with ${stats.totalWords} words from ${stats.uniqueDomains} domains\n`);
    
    // Search for stock-related content
    console.log('🔎 Searching for stock news in India...');
    const searchQueries = [
      'stocks India',
      'share market India', 
      'NIFTY SENSEX',
      'Indian stock market',
      'business news India',
      'financial news India'
    ];
    
    const allResults = [];
    
    for (const query of searchQueries) {
      console.log(`   Searching: "${query}"`);
      const searchResponse = await axios.post(`${baseUrl}/api/v1/search`, {
        query,
        limit: 5
      });
      
      const results = searchResponse.data.results;
      allResults.push(...results);
    }
    
    // Remove duplicates based on URL
    const uniqueResults = allResults.filter((result, index, self) => 
      index === self.findIndex(r => r.url === result.url)
    );
    
    // Sort by relevance score
    uniqueResults.sort((a, b) => b.relevanceScore - a.relevanceScore);
    
    console.log(`\n📈 Found ${uniqueResults.length} unique relevant articles\n`);
    
    // Generate JSON Report
    const jsonReport = {
      reportType: 'Stock News India Report',
      generatedAt: new Date().toISOString(),
      crawlerStats: stats,
      searchQueries: searchQueries,
      totalArticles: uniqueResults.length,
      articles: uniqueResults.map(article => ({
        title: article.title,
        url: article.url,
        description: article.description,
        publishDate: article.publishDate,
        wordCount: article.wordCount,
        qualityScore: article.qualityScore,
        relevanceScore: article.relevanceScore,
        topics: article.topics,
        contentType: article.contentType
      }))
    };
    
    // Generate Markdown Report
    const markdownReport = `# Stock News India Report

**Generated:** ${new Date().toLocaleString()}
**Total Articles:** ${uniqueResults.length}
**Total Pages Crawled:** ${stats.totalPages}
**Total Words:** ${stats.totalWords}
**Success Rate:** ${stats.successRate}%

## Crawler Statistics
- **Pages Crawled:** ${stats.totalPages}
- **URLs Processed:** ${stats.totalUrls}
- **Words Extracted:** ${stats.totalWords}
- **Failed Crawls:** ${stats.totalFailed}
- **Average Quality:** ${stats.averageQuality}
- **Unique Domains:** ${stats.uniqueDomains}
- **Crawl Duration:** ${stats.duration} seconds

## Top Stock News Articles

${uniqueResults.map((article, index) => `
### ${index + 1}. ${article.title}

**URL:** ${article.url}
**Published:** ${article.publishDate || 'Not specified'}
**Word Count:** ${article.wordCount}
**Quality Score:** ${article.qualityScore}
**Relevance Score:** ${article.relevanceScore.toFixed(2)}

**Description:** ${article.description}

**Key Topics:** ${article.topics.slice(0, 10).join(', ')}${article.topics.length > 10 ? '...' : ''}

---
`).join('')}

## Search Queries Used
${searchQueries.map(query => `- "${query}"`).join('\n')}

## Summary
This report contains ${uniqueResults.length} relevant articles about stocks and business news in India, crawled from ${stats.uniqueDomains} different domains. The articles cover various aspects of the Indian stock market, including SENSEX, NIFTY, business news, and financial updates.

*Report generated by Web Crawler AI*
`;
    
    // Save reports
    const fs = require('fs');
    fs.writeFileSync('stock_news_report.json', JSON.stringify(jsonReport, null, 2));
    fs.writeFileSync('stock_news_report.md', markdownReport);
    
    console.log('📄 Reports generated successfully!');
    console.log('   📋 stock_news_report.json');
    console.log('   📋 stock_news_report.md');
    
    // Display summary
    console.log('\n📊 Report Summary:');
    console.log(`   Articles found: ${uniqueResults.length}`);
    console.log(`   Top relevance score: ${uniqueResults[0]?.relevanceScore.toFixed(2) || 'N/A'}`);
    console.log(`   Average quality: ${stats.averageQuality}`);
    console.log(`   Domains covered: ${stats.uniqueDomains}`);
    
    // Show top 3 articles
    console.log('\n🏆 Top 3 Articles:');
    uniqueResults.slice(0, 3).forEach((article, index) => {
      console.log(`   ${index + 1}. ${article.title}`);
      console.log(`      Relevance: ${article.relevanceScore.toFixed(2)} | Quality: ${article.qualityScore}`);
    });
    
  } catch (error) {
    console.error('❌ Error generating report:', error.message);
    if (error.response) {
      console.error('Response status:', error.response.status);
      console.error('Response data:', error.response.data);
    }
  }
}

// Run the report generator
generateStockNewsReport(); 